import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313032",
        "inverse-surface": "#e5e1e4",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-fixed-variant": "#004c6e",
        "surface-container-high": "#2a2a2c",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-dim": "#131315",
        "secondary-container": "#00a2e6",
        "on-secondary-fixed": "#001e2f",
        "on-surface": "#e5e1e4",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#89ceff",
        "primary-fixed": "#e9ddff",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f21",
        "on-primary-fixed": "#23005c",
        "surface": "#131315",
        "on-surface-variant": "#cbc3d7",
        "secondary": "#89ceff",
        "on-secondary": "#00344d",
        "surface-container-highest": "#353437",
        "on-background": "#e5e1e4",
        "on-primary-fixed-variant": "#5516be",
        "on-primary-container": "#340080",
        "on-tertiary-fixed": "#002113",
        "surface-container-low": "#1c1b1d",
        "surface-bright": "#39393b",
        "on-secondary-container": "#00344e",
        "secondary-fixed": "#c9e6ff",
        "inverse-primary": "#6d3bd7",
        "outline": "#958ea0",
        "tertiary": "#4edea3",
        "on-tertiary": "#003824",
        "on-primary": "#3c0091",
        "tertiary-fixed": "#6ffbbe",
        "outline-variant": "#494454",
        "background": "#131315",
        "primary-fixed-dim": "#d0bcff",
        "surface-tint": "#d0bcff",
        "tertiary-container": "#00a572",
        "primary-container": "#a078ff",
        "primary": "#d0bcff",
        "error": "#ffb4ab",
        "on-tertiary-container": "#00311f",
        "surface-variant": "#353437",
        "text-primary": "#ffffff",
        "text-secondary": "#94a3b8",
        "border-glass": "rgba(255, 255, 255, 0.1)",
        "surface-glass": "rgba(255, 255, 255, 0.03)",
        "grid-dot": "#1e293b",
        "surface-base": "#020617"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "grid-size": "32px",
        "sidebar-width": "320px",
        "header-height": "64px",
        "gutter": "24px",
        "stack-gap": "16px",
        "margin-page": "32px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
export default config;
