import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb783",
        "error-container": "#93000a",
        "on-primary-fixed": "#07006c",
        "inverse-on-surface": "#313032",
        "tertiary-container": "#d97721",
        "on-tertiary-container": "#452000",
        "tertiary": "#ffb783",
        "on-secondary-fixed": "#001f26",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "surface-tint": "#c0c1ff",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed": "#acedff",
        "surface-dim": "#131315",
        "surface-container": "#201f22",
        "secondary": "#4cd7f6",
        "on-primary-container": "#0d0096",
        "secondary-container": "#03b5d3",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-background": "#e5e1e4",
        "surface-variant": "#353437",
        "on-secondary": "#003640",
        "grid-dot": "#1e293b",
        "outline": "#908fa0",
        "inverse-primary": "#494bd6",
        "on-tertiary-fixed-variant": "#703700",
        "primary-fixed": "#e1e0ff",
        "on-error-container": "#ffdad6",
        "on-surface": "#e5e1e4",
        "surface-container-lowest": "#0e0e10",
        "on-error": "#690005",
        "inverse-surface": "#e5e1e4",
        "text-primary": "#ffffff",
        "border-glass": "rgba(255, 255, 255, 0.1)",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-fixed": "#301400",
        "on-tertiary": "#4f2500",
        "primary": "#c0c1ff",
        "surface": "#131315",
        "text-secondary": "#94a3b8",
        "on-secondary-fixed-variant": "#004e5c",
        "surface-bright": "#39393b",
        "surface-base": "#020617",
        "background": "#131315",
        "outline-variant": "#464554",
        "surface-glass": "rgba(255, 255, 255, 0.03)",
        "on-secondary-container": "#00424e",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-surface-variant": "#c7c4d7",
        "surface-container-low": "#1c1b1d",
        "surface-container-highest": "#353437"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "grid-size": "32px",
        "sidebar-width": "320px",
        "header-height": "64px",
        "gutter": "24px",
        "stack-gap": "16px",
        "margin-page": "32px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
export default config;
