"""Add missing DB indexes and fix nullable conversation_id

Revision ID: 30602981bd78
Revises: e2cfa0d41e2e
Create Date: 2026-07-25 17:33:28.359740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30602981bd78'
down_revision: Union[str, None] = 'e2cfa0d41e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_execution_steps_execution_id', 'execution_steps', ['execution_id'], unique=False)
    op.alter_column('executions', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_executions_conversation_id', 'executions', ['conversation_id'], unique=False)
    op.create_index('ix_executions_user_id', 'executions', ['user_id'], unique=False)
    op.create_index('ix_memory_episodes_embedding_hnsw', 'memory_episodes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memory_episodes_user_id', 'memory_episodes', ['user_id'], unique=False)
    op.create_index('ix_memory_facts_embedding_hnsw', 'memory_facts', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memory_facts_user_id', 'memory_facts', ['user_id'], unique=False)
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.drop_index('ix_memory_facts_user_id', table_name='memory_facts')
    op.drop_index('ix_memory_facts_embedding_hnsw', table_name='memory_facts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_memory_episodes_user_id', table_name='memory_episodes')
    op.drop_index('ix_memory_episodes_embedding_hnsw', table_name='memory_episodes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_executions_user_id', table_name='executions')
    op.drop_index('ix_executions_conversation_id', table_name='executions')
    op.alter_column('executions', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_execution_steps_execution_id', table_name='execution_steps')
    # ### end Alembic commands ###
